### ISSUE TITLE
Falta import en instrucciones producción Python

### ISSUE THREAD

**Issue by donbalon4** [TransbankDevelopers/transbank-developers-docs#320]
Hola, estoy tratando de configurar una integración a producción siguiendo la documentación:
![imagen](https://user-images.githubusercontent.com/3063810/108260217-d3c9de80-7140-11eb-88db-6cc9238d67c7.png)

El problema es que al parecer falta un import para ejecutar los comandos para WebpayPlus.

¿Me pueden indicar qué es lo que debo importar, por favor?
De antemano, muchas gracias.

**Comment by gonzunigad** [comment]
Hola @donbalon4. Gracias por el reporte. Vamos a revisar para poder mejorar esa documentación. ¿Finalmente sabes que líneas faltaba agregar?

**Comment by donbalon4** [comment]
hola @gonzunigad , sí gracias, al final modifiqué este archivo: `transbank/webpay/webpay_plus/__init__.py`
Dejo un ejemplo acá, por si le sirve a alguien más:

```
from transbank.common.integration_type import IntegrationType

webpay_plus_default_commerce_code = "xxxxxxxxx"
webpay_plus_mall_default_commerce_code = "xxxxxxx"
mall_default_child_commerce_codes  = ['xxxxxxxxx', 'xxxxxxxxx']
default_api_key = "xxxxxxxxxxxxxx"
default_integration_type = IntegrationType.LIVE
webpay_plus_deferred_commerce_code = "xxxxxxxxxxxx"
webpay_plus_mall_deferred_default_commerce_code = "xxxxxxxxxxx"
mall_deferred_default_child_commerce_codes  = ['xxxxxxxxxxx', 'xxxxxxxxxxxx']
```

Saludos!

**Comment by gonzunigad** [comment]
cc @ffiebig
