### ISSUE TITLE
Problemas con tarjetas de credito del extranjero

### ISSUE THREAD

**Issue by PatrickCaneloDigital** [TransbankDevelopers/transbank-developers-docs#383]
Como cliente, usuario y desarrollador de Transbank:
Tengo varios clientes que me mencionaron que usuarios con tarjetas de credito del extranjero no pueden efectuar compras.
Yo mismo acabo de toparme con ese problema en distintas tiendas y en las versiones que desarrollo con el plugin de transbank: 
Desde Ripley, Paris, PCFactory y otros que ocupan la implementacion de transbank mis compras con tarjeta de visa del extranjero fallan siempre. También tengo conocidos con tarjetas VISA de otros paises que tienen problemas similares.

En mi caso por ejemplo compras con aerolineas suelen funcionar bien, pero en retail no.
He verificado con mi banco y me dicen que el problema es por el lado de implementacion.

Mit Tarjeta VISA tiene una verificacion 3D, es decir una vez confirmado numero tarjeta, fecha caducidad y codigo verificacion, me tira a una pagina de mi banco donde me pide una accion adicional.
Siempre llego hasta alli y confirmo, pero despues me devuelve a la pagina de comercio con el mensaje que la transacción falló.
Yo hable y verifique con mi banco y no es un problema de saldo, de hecho en mi banco me cnfirman que hasta allí todo bien, lo que falta despues de la verificación 3D es la accion de efectivamente efectuar la compra...

Hay algo en la implementación de tranbank que bloquea o inhabilita tarjetas de credito del extranjero.
Años atras hice una investigacion a fondo, eso era con la API SOAP y en ese momento habia campos que se enviaban al reves hacia mi banco, pero el problema actual no esta ligado a eso al parecer, es como que simplemente faltara un paso.

No me pasa con todos los sistemas de compra online en chile, pero FPay, plugin Transbank y otros retail mayores tienen todos implementaciones que no funcionan con tarjetas de credito extranjeras, cosa que ha obligado a varios clientes mios a seguir ocupando Paypal en vez de transbank

![imagen](https://user-images.githubusercontent.com/21183922/113898532-f750f300-9799-11eb-8466-3205db603b26.png)

![imagen](https://user-images.githubusercontent.com/21183922/113899307-aab9e780-979a-11eb-8f86-f2fb7f3c4b18.png)

**Comment by gonzunigad** [comment]
Hola @PatrickCaneloDigital. Este no es un canal de soporte. Te recomeidno publicar el mismo mensaje en Slack: https://join-transbankdevelopers-slack.herokuapp.com/

**Comment by PatrickCaneloDigital** [comment]
no estoy pidiendo soporte, es un problema del plugin ;-)

**Comment by gonzunigad** [comment]
Este repositorio es donde la comunidad puede mejorar la documentación que
está disponible en transbankdevelopers.cl. Acá no hay nada de plugins ni
código :)

Por otro lado, los plugins y SDk solo integran el API, por lo que problemas
con pago de tarjetas no tienen relacion con el código de los plugins. Es
probablemente un tema realcionado a como opera el sistema autorizador de
transacciones y alguna cnfiguración asociada a tu código de comercios,
cosas que no tienen que ver con código ni integraciones, pero que podríamos
apoyarte en Slack.


GONZALO DE-SPIRITO

*FRESHWORK* STUDIO CHILE

+569 8815 3776 |  ***@***.******@***.***
