### ISSUE TITLE
Verifone UX300

### ISSUE THREAD

**Issue by xevilmaxx** [TransbankDevelopers/transbank-developers-docs#464]
Hi, 
I would really like to adopt your library.
I'm currently working with Verifone UX300 POS model.

I used POSAutoservicio singleton inside your library.
Tried to connect POS with USB and /or with RS232 (dedicated cable), but cannot initialize payment.
On POS i can put "Cash Register" to work with following protocols:
* None (not the case)
* 17 (tried but receiving **NAK**)
* VFI (tried but seems even not to communicate)
* MDB (not the case)

Here is my code:
```csharp
                POSAutoservicio.Instance.OpenPort("COM1", 115200);

                Console.WriteLine("-> <-");
                Console.ReadLine();

                //var res = POSAutoservicio.Instance.Initialization().Result;
                //Console.WriteLine("Result: " + res);

                //EventHandler para los mensajes intermedios.
                POSAutoservicio.Instance.IntermediateResponseChange += NewIntermediateMessageReceived;

                try
                {
                    var isPOSOk = POSAutoservicio.Instance.Poll().Result;
                    Console.WriteLine($"isPOSOk: {isPOSOk}");
                }
                catch(Exception ex)
                {
                    Console.WriteLine(ex);
                }
                

                Console.WriteLine("Press any key to start payment");
                Console.ReadLine();
                Console.WriteLine("Init payment");
                var response = POSAutoservicio.Instance.Sale(51, "123456789", true, true).Result;

                Console.WriteLine(JsonConvert.SerializeObject(response));

                Console.WriteLine("Press any key to exit");
                Console.ReadLine();
                POSAutoservicio.Instance.ClosePort();
```

I tried to analyze your LCR, by using this site:
https://toolslick.com/math/bitwise/xor-calculator
But cannot figure out how LCR is made.

For example here is your command:
    02 30 31 30 30 03 02
but through website with different combinations of command i cannot obtain LCR = 02

**Could you kaindly suggest me how to configure Verifone UX300 in order to make it work properly with your library?**

I also found this docs on your site but i cannot figure out how to configure POS from it.
[manual-integracion-pos-autoservicio-4.3.pdf](https://github.com/TransbankDevelopers/transbank-developers-docs/files/7926672/manual-integracion-pos-autoservicio-4.3.pdf)

**Comment by mastudillot** [comment]
hi, you can try change the baudrate to 19200

**Comment by xevilmaxx** [comment]
will try asap, for now i was trying with 115200

**Comment by xevilmaxx** [comment]
Here is output i continue to get:

```
Out (Hex): 02 30 31 30 30 03 02
Out (ASCII): 0100
In: 15
isPOSOk: False
Press any key to start payment

Init payment
Out (Hex): 02 30 32 30 30 7C 35 31 7C 31 32 33 34 35 36 37 38 39 7C 31 7C 31 03 34
Out (ASCII): 0200|51|123456789|1|14
In: 15
System.AggregateException: One or more errors occurred. (Unable to execute sale on pos)
 ---> Transbank.Exceptions.AutoservicioExceptions.TransbankSaleException: Unable to execute sale on pos
 ---> Transbank.Exceptions.CommonExceptions.TransbankException: Unable to send message to COM1
   at Transbank.Utils.Serial.WriteData(String payload, Boolean intermediateMessages, Boolean saleDetail, Boolean printOnPOS) in C:\Users\maxym.oboyshev\source\repos\MyTests\TransbankPosSDK\Utils\Serial.cs:line 171
   at Transbank.POSAutoservicio.POSAutoservicio.Sale(Int32 amount, String ticket, Boolean sendVoucher, Boolean sendStatus) in C:\Users\maxym.oboyshev\source\repos\MyTests\TransbankPosSDK\POSAutoservicio.cs:line 115
   --- End of inner exception stack trace ---
   at Transbank.POSAutoservicio.POSAutoservicio.Sale(Int32 amount, String ticket, Boolean sendVoucher, Boolean sendStatus) in C:\Users\maxym.oboyshev\source\repos\MyTests\TransbankPosSDK\POSAutoservicio.cs:line 120
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at VerifoneSDK.Program.Main(String[] args) in C:\Users\maxym.oboyshev\source\repos\MyTests\VerifoneSDK\Program.cs:line 60

```

Same message on different baud rates and settings when answering something.
Any ideas?
Thanks.

**Comment by mastudillot** [comment]
You can check the connection interface if you use USB or serial port.

Check the status of the Self-service POS port, for that you can enter the technical menu by pressing the ok or green button, and keys 9 and 1, sequentially

RUT 1111111-1
Password of the month 124265

**Comment by mastudillot** [comment]
You can join slack in the following [link](https://join-transbankdevelopers-slack.herokuapp.com/) to help you better
