### ISSUE TITLE
API breaking change in `card_digits`

### ISSUE THREAD

**Issue by zugzwang** [TransbankDevelopers/transbank-developers-docs#509]
During some hours in 24.09.2024, we experienced issues because the transaction confirmation API returned the card digits in a different format.

Usually, `response['card_detail']['card_digits']` carries an integer value with the last 4 digits of the card used, e.g. `1234`.

For some hours, the API returned instead a string of the form `"XXXXXXXXXXXX1234"` and caused us serious production issues until a hotfix was implemented on our side to parse both formats.

I have the following questions:

- Could you confirm what happened? I don't see any incident reported in the [status page](https://status.transbankdevelopers.cl/). Should I report an incident?
- Do you have a page where I can see past and upcoming API changes like this one? If so can you point us to it?

Thanks

**Comment by zugzwang** [comment]
EDIT: Where it reads `card_digits` I meant `card_number`.

I forgot to add; the API reference says that `card_number` is "Last 4 numbers of the cardholder's credit card. Maximum length: 19." and is a string value, not an integer value as I mentioned above. I was specifically wondering about the maximum length. Could you comment on that too.

**Comment by Matiasnickolas** [comment]
Hi zugzwang!, The API documentation has not changed, the maximum length is 19. If you received any abnormal response from the API in the production environment, please send an email to soporteweb@transbank.cl with any background information you have so they can assist you

**Comment by zugzwang** [comment]
Hello @Matiasnickolas, as described clearly in this issue, the API sent responses that do not correspond to the documentation, nor to the behavior for the past years. I am not seeking any documentation change, although I do wonder on the maximum length part.

I will reach out to soporteweb@transbank.cl, and I will come back here if I do not get a meaningful response about this incident.

Thanks!
